version: "3.5"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.52
    command: --query.ui-config=/etc/jaeger/jaeger-ui.json --collector.otlp.enabled=true --prometheus.server-url=http://prometheus:9090 --prometheus.query.support-spanmetrics-connector=true
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    volumes:
      - ./Configs/jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    ports:
      - "127.0.0.1:16686:16686"
    networks:
      - backend
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: --config /etc/otelcol/otel-collector-config.yml
    volumes:
      - ./Configs/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    ports:
      - "127.0.0.1:4317:4317"
    networks:
      - backend
    depends_on:
      - jaeger
 
  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./Configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - backend
  
  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/mnt/config/loki-config.yml
    volumes:
      - ./Configs/loki.yml:/mnt/config/loki-config.yml
    ports:
      - "127.0.0.1:3100:3100"
    networks:
      - backend
  
  grafana:
    image: grafana/grafana-enterprise
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./Configs/grafana.ini:/etc/grafana/grafana.ini
      - ./Configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./Configs/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./Configs/dotnet-otel-dashboard.json:/etc/grafana/provisioning/dashboards/dotnet-otel-dashboard.json
      - ./Configs/logs-dashboard.json:/etc/grafana/provisioning/dashboards/logs-dashboard.json
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - backend

  weather-service:
    build:
      dockerfile: Dockerfile
      context: .
    image: dotnet-otel-grafana-prometheus
    environment:
      - ServiceName=weather-api
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - backend
      
networks:
  backend:
